export const themeConatus = {
  themeId: "conatus-v1",
  name: "Conatus Ambiental",
  colors: {
    primary: "#1a7a5c",
    primaryDark: "#145e47",
    primaryLight: "#22a87e",
    accent: "#0d3b2e",
    accentLight: "#1a5c47",
    dark: {
      bg: "#0f1f1a",
      bgAlt: "#142b23",
      surface: "#1a3a2e",
      text: "#e8f5f0",
      textSecondary: "#a8cfc0",
      textMuted: "#6b9e8c",
      border: "#2a5a48",
    },
    light: {
      bg: "#f5faf8",
      bgAlt: "#edf6f2",
      surface: "#ffffff",
      text: "#0f2a20",
      textSecondary: "#3a6b55",
      textMuted: "#6b9e8c",
      border: "#c8e0d5",
    },
    chart: ["#1a7a5c", "#2aa88e", "#0d5c45", "#45c9a8", "#0a3d2e"],
  },
  fonts: {
    heading: "'Plus Jakarta Sans', sans-serif",
    body: "'Inter', sans-serif",
    mono: "'JetBrains Mono', monospace",
  },
  typography: {
    title: { size: "2.5rem", weight: 700, lineHeight: 1.2 },
    subtitle: { size: "1.25rem", weight: 400, lineHeight: 1.4 },
    heading: { size: "1.75rem", weight: 600, lineHeight: 1.3 },
    body: { size: "1rem", weight: 400, lineHeight: 1.6 },
    caption: { size: "0.875rem", weight: 400, lineHeight: 1.4 },
    small: { size: "0.75rem", weight: 400, lineHeight: 1.4 },
  },
  spacing: {
    slide: { padding: "3rem 4rem" },
    section: { gap: "2rem" },
    content: { gap: "1.5rem" },
    bullet: { gap: "0.75rem" },
  },
  radius: {
    sm: "0.375rem",
    md: "0.5rem",
    lg: "0.75rem",
    xl: "1rem",
  },
};
